### ISSUE TITLE
error while installing yarn [Error: Couldn't find the python binary. Make sure it's installed and in your $PATH]

### ISSUE THREAD

**Issue by AliMostafaRadwan** [leemonade/leemons#10]
having and error while installing yarn in **/examples/demo**

after some loading i get this error >>

`error /home/aradwan/LMS/leemons-main/node_modules/youtube-dl-exec: Command failed.
Exit code: 1
Command: npx bin-version-check-cli python ">=2"
Arguments: 
Directory: /home/aradwan/LMS/leemons-main/node_modules/youtube-dl-exec
Output:
Error: Couldn't find the `python` binary. Make sure it's installed and in your $PATH.`

**Comment by MIGUELez11** [comment]
Which OS are you using?

This error is probably related to not having Python 3 or major. If you have it installed, make sure it can be accessed through `python` not only `python3`

**Comment by AliMostafaRadwan** [comment]
thanks i fixed it like you said ... the problem was the **python3** didn't have **python** as an **alias**

I fixed it by running `sudo apt-get install python-is-python3 -y`
