### ISSUE TITLE
leemons-connector-bookshelf not found on npm i

### ISSUE THREAD

**Issue by ermarkar** [leemonade/leemons#25]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/leemons-connector-bookshelf - Not found
npm ERR! 404
npm ERR! 404  'leemons-connector-bookshelf@0.0.1-beta.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'demo'
npm ERR! 404

**Comment by MIGUELez11** [comment]
Hi there, right now isn't published, we are currently working on it as a monorepo, use the docker installation or clone the repository as indicated [in the docs](https://leemonade.github.io/leemons-docs/category/getting-started) ☺.

**Comment by ermarkar** [comment]
Thanks for the update, i followed your document, there is package folder parallels to demo, i guess i have to install the dependency one by one from local.. If you can update installation page of yours.

**Comment by ermarkar** [comment]
so it works with yarn? i was trying with the npm

**Comment by MIGUELez11** [comment]
We use yarn when developing, but time to time we test with npm, and the times we tried, worked perfectly, but yes, we do recommend using yarn ☺.

**Comment by ermarkar** [comment]
worked with yarn not working with npm, i guess you need to mention that it works with yarn only, and highight that node > 16.14 is required, i almost spend whole day to find this!! 

thanks for your help

**Comment by ermarkar** [comment]
in nutshell, it does not work on windows.

running yarn dev again says

```
2022-12-19T10:44:51.681Z ERROR   E11000 duplicate key error collection: leemons.plugins_widgets::widget-zones index: key_1 dup key: { key: "plugins.users.user-detail" }
MongoServerError: E11000 duplicate key error collection: leemons.plugins_widgets::widget-zones index: key_1 dup key: { key: "plugins.users.user-detail" }
    at D:\projects\leemons\node_modules\mongodb\lib\operations\insert.js:53:33
    at D:\projects\leemons\node_modules\mongodb\lib\cmap\connection_pool.js:273:25
    at handleOperationResult (D:\projects\leemons\node_modules\mongodb\lib\sdam\server.js:327:20)
    at operationDescription.cb (D:\projects\leemons\node_modules\mongodb\lib\cmap\connection.js:562:17)
```

running yarn front not working and it says

```
$ yarn clear && NODE_ENV=production ts-node config/index.ts .
$ rimraf build
[Error: ENOENT: no such file or directory, open 'D:\projects\leemons\packages\leemons-react\enabledPlugins.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\projects\\leemons\\packages\\leemons-react\\enabledPlugins.json'
}
Note: This command was run via npm module 'win-node-env'
```

**Comment by ermarkar** [comment]
is there any running demo?

**Comment by Cerberupo** [comment]
For the first error it seems that when you started for the first time leemons failed some plugin and in the database were created some things if and others not, and when you restart it tries again to create certain records and fails because they are already created, deleting the database and restarting should be solved (I understand that you never got to start leemons and therefore should not see a problem with deleting the database).

**Comment by MIGUELez11** [comment]
Also, related to windows problem, we are finishing the final validations to update the main branch with the latest code, it should be done in the following days.

About a running demo, you can always follow the docker docs, or to test it installation free, you can register at [Public leemons beta](https://leemons.io/product/discover-beta)

**Comment by Cerberupo** [comment]
For the second error you have tried `yarn front:dev` ?

**Comment by ermarkar** [comment]
not wokint fornt:dev as well, i am trying it from last week, if you can mention on your installation page that for windows it is still in progress, i could directly start with docker
