### ISSUE TITLE
What branch to use for development

### ISSUE THREAD

**Issue by wassimbj** [leemonade/leemons#29]
Hello 👋🏼😁

I'm wondering what branch should I clone to make changes and actually use it in production ? I'm trying to add and remove some features that are not needed for now. should I clone the `demo` or `master` branch ?

**Comment by MIGUELez11** [comment]
Hiii ☺.

We are currently making testings with schools on the `testings` branch, so I would recommend you to use that one.

But if you feel comfortable with less production code, you may use the dev branch, but that one has too new and untested code.

The demo and main branch currently have very old code, as we are making the last tests and comprobations to merge testings to main.

**Comment by wassimbj** [comment]
Okay, thank you so much 🫡😁
