### ISSUE TITLE
I can't be able to access the dashboard

### ISSUE THREAD

**Issue by AbdoALPOP** [leemonade/leemons#37]
I complete the setup but while login as an Admin, it is display the setup pages again.
I used docker.

**Comment by MIGUELez11** [comment]
I'm sorry for the delay in responding. There may be a couple of errors causing this issue. One possible cause is that you're logging in again as the `super admin`, which is the very first email and password you registered. Instead, please log in as the admin you created.

Another possibility is that some part of the system is hung up. You can try visiting the URL HOST/users/login. If you're not logged in, or if you're logged in as an admin, it should navigate you out of the super-admin interface.

I hope this helps you resolve the issue. Again, my apologies for the late response.

**Comment by MIGUELez11** [comment]
I close this for inactivity. You can reopen it when needed 😄.
