### ISSUE TITLE
black page is visible

### ISSUE THREAD

**Issue by lalit10-patidar** [leemonade/leemons#38]
I am installing the front and backend code locally...but it's showing a black page (http://localhost:3000 or http://localhost:8080)

![image](https://github.com/leemonade/leemons/assets/89124079/86a93fbb-90bc-4a19-bcda-a434d1697706)

**Comment by MIGUELez11** [comment]
Hi ☺, 

First of all, to know what is happening, I would like to know a few things.

1. Which operating system are you using
2. Which node version you have installed
3. How are you running the backend server
4. How are you running the frontend server


Also to have more insights, what happens when you visit [http://localhost:8080/users/login]()?

**Comment by lalit10-patidar** [comment]
thanks for quick response

1. Which operating system are you using
 => I am using window  11
2. Which node version you have installed 
 => node version  v18.16.0
3. How are you running the backend server
 => First I installed the package using `yarn install` and then ran the backend server  `yarn dev`
4.  How are you running the frontend server
=>  ran the backend server  `yarn front`
![image](https://github.com/leemonade/leemons/assets/89124079/8dc3ee47-2672-4799-8523-9626c1c4eadf)

![Screenshot 2023-05-12 165742](https://github.com/leemonade/leemons/assets/89124079/056dc7f6-bef9-4338-b770-e553f164a62a)

**Comment by MIGUELez11** [comment]
Okay, looks like the frontend had some errors while compiling, I'm going to have a look and inform you how we can solve it ☺.

**Comment by lalit10-patidar** [comment]
@MIGUELez11 any update?

**Comment by MIGUELez11** [comment]
Sorry, I've been a little busy, I hope I can look at it tomorrow ☺

**Comment by MIGUELez11** [comment]
Okay, I've been looking at it, and looks like you are using an older version of leemons, we are currently recommending to use the `demo`  branch, as it is up-to-date, the @socket-io/services dependency has been removed since then, so the problem should be gone in the new version.

**Comment by MIGUELez11** [comment]
Demo is not recommended anymore, you should use main. But as this error should be fixed, I close this issue.
