### ISSUE TITLE
Error en menu-builder

### ISSUE THREAD

**Issue by AdolfoJulcamoro** [leemonade/leemons#44]
Al momento de ejecutar la primera parte (el back, con el comando yarn dev) se está presentado el siguiente error:

`Error: Menu item with key 'plugins.scores.scores' for menu 'plugins.menu-builder.main' not exists`

Lo que visto es que esa key no se ha registrado en base de datos y por eso falla, pero no sé en que momento se debe hacer ese registro de base de datos. Estoy haciendo uso de la rama main, que veo ha sido recientemente mergeada desde la rama demo.

Adicionalmente, les comento que este error no se presentada antes de que hagan el merge desde demo.

**Comment by MIGUELez11** [comment]
Buenas :D

¿Puede ser que tuvieses ya la base de datos creada en la anterior versión de la rama main?

Ha habido muchos cambios desde la anterior versión de main y la actual, en el caso de que hayas usado la anterior versión, te recomiendo hacer un backup de tu base de datos, borrarla y volver a arrancar leemons, así debería funcionarte.

Siento muchísimo si esta versión ha hecho incompatible tu instalación

**Comment by AdolfoJulcamoro** [comment]
Algo que he visto es que un nuevo package agregado esta generando el conflicto, se trata de attendance-control. En esta  [línea](https://github.com/leemonade/leemons/blob/demo/packages/leemons-plugin-attendance-control/config/constants.js#L23) se indica que se asocia a scores. La inserción de attendance se intenta hacer antes que scores y por eso falla

**Comment by MIGUELez11** [comment]
Perfecto, eso me ha ayudado a encontrar el más que probable error, se trata del archivo `packages/leemons-plugin-attendance-control/events.js`, en la línea 60 deberías encontrar algo tal que así:

https://github.com/leemonade/leemons/blob/c60f494970c4dd6fb5c501c6c7f0672ab0c2f8ac/packages/leemons-plugin-attendance-control/events.js#L59-L64

¿Podrías cambiar `plugins.scores:init-permissions` por `plugins.scores.init-menu`?

Antes de volver a ejecutar el servidor tras este cambio, te pido que vuelvas a borrar la base de datos, pues probablemente tengas la instalación corrupta actualmente, y en caso de que funcione, hago un fix, o si lo prefieres, puedes hacer un pull request y aparecer como contribuidor de Leemons.

**Comment by AdolfoJulcamoro** [comment]
De acuerdo, más tarde envío el PR. Con el cambio ya quedó habilitada la aplicación
