### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'connector')

### ISSUE THREAD

**Issue by ziad696** [leemonade/leemons#48]
I'm new and want to test to install leemons using yarn so after i run yarn dev, this error show, any help is appreciated, thank you

![image](https://github.com/leemonade/leemons/assets/66814551/bff169d2-d711-4c6b-a5dd-36a58c8d06d2)

**Comment by MIGUELez11** [comment]
Hi @ziad696!!

Several things comes to my mind, the very first one is that you might not have installed yarn dependencies, run `yarn install` from the root of the workspace and try to run again (as you are telling me you are using yarn, probably is not the error).

Other things that comes to my mind are that mysql or leemons-connector-bookshelf is not installed in `examples/demo`.

Finally, maybe sql and/or mongo are not setted up correctly in `examples/demo/config/database.js`.

**Comment by ziad696** [comment]
thanks for your answer, actually as documentation says i only do "yarn install" in examples/demo, so i do only in that folder, but to make sure, these thing i just do is

1. reset my database, i only use mysql, and dont have or setup monggo, is that ok?
2. yarn install in the root of the workspace
3. yarn install in examples/demo folder
4. yarn dev -> same problem still happen

I believe the app is able to connect to database since i see table and row created, here i attach my database.js, maybe i have something wrong here

![image](https://github.com/leemonade/leemons/assets/66814551/f6df8a90-93dc-4f08-8713-8034914cab1e)

**Comment by MIGUELez11** [comment]
Yes, in the latest version of Leemons, although it hasn't been documented yet, a MongoDB connection is required to start the application. I recommend using a Mongo Atlas free tier if you're using the latest code from the `main` branch. I encountered the same error when I removed this connection from my installation.

You can find the MongoDB configuration inside the `examples/demo/database.js` file.

```js
 mongo: {
      connector: 'mongoose',
      settings: {
        database: process.env['NOSQL_DATABASE'],
        authDatabase: process.env['NOSQL_AUTH_DATABASE'],
        username: process.env['NOSQL_USERNAME'],
        password: process.env['NOSQL_PASSWORD'],
        port: process.env['NOSQL_PORT'],
        host: process.env['NOSQL_HOST'],
        srv: process.env['NOSQL_SRV'],
        pool: {
          min: 5,
          max: 1000,
        },
      },
    },
```


If you use mongo atlas, you'll need to set `srv` to true, I do use env variables, but you can define them in that file directly.

**Comment by ziad696** [comment]
thanks, it resolve my problem, i have finish installation

**Comment by ziad696** [comment]
thanks, it resolve my problem, i have finish installation

**Comment by Prithviraj-debug** [comment]
Hi, I'm facing the same issue and I don't know how to add atlas configurations in the database.js file.

**Comment by Prithviraj-debug** [comment]
Hi, I'm facing the same issue and I don't know how to add atlas configurations in the database.js file.
