### ISSUE TITLE
Missing Backlog Section in Kanban Board - Tasks Not Visible

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#56]
The Kanban board lacks a dedicated section for "Backlog," which results in newly added tasks being hidden without any visibility on the board. As a result, once a task is added to the backlog, it becomes challenging to track, prioritize, and manage those tasks effectively within the current Kanban setup.

Current Behavior:
1. Adding a task to the backlog does not make it visible on the Kanban board.
2. There is no designated section or column for tasks residing in the backlog.

Expected Behavior:
1. When a task is added to the backlog, it should be clearly visible in a dedicated "Backlog" section on the Kanban board.
2. Having a distinct backlog section will facilitate task management and enable tutors to prioritize and assign tasks from the backlog when required.

The addition of a backlog section to the Kanban board is crucial for better task organization, workflow management, and ensuring that no tasks go unnoticed or unattended. By incorporating this enhancement, tutors will have a more streamlined experience in managing tasks throughout their lifecycles. Please consider implementing this feature to enhance the overall usability and effectiveness of the Kanban board.

**Comment by MIGUELez11** [comment]
The backlog column is currently only visible from the backlog page, which is accesed from the backlog menu-item.
It's intended to not show the backlog column in the dashboard as it states the actual important information, the backlog is not crucial so it's removed from dashboard for you.

**Comment by fmniloyuk** [comment]
@MIGUELez11  I'm unable to locate the specific page or menu you mentioned. Could you kindly share a screenshot with me?

**Comment by MIGUELez11** [comment]
I'm on my phone, but I can share a screenshot of a teacher ![screenshot of leemons showing the kanban](https://github.com/leemonade/leemons/assets/27650532/6e2da589-c1ea-4dfb-9020-e863446e94e7)
