### ISSUE TITLE
Blank Screen after Image Upload - Image Not Visible in Media Library

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#57]
An issue has been identified when uploading images to the media library, causing the screen to go blank. Additionally, the uploaded image does not appear in the media library after the upload process is completed.

Steps to Reproduce:
1. Log in to the platform.
2. Navigate to the media library section.
3. Upload an image from local storage.

Expected Behavior:
1. The image upload process should complete successfully without any errors.
2. After uploading, the uploaded image should be visible and accessible in the media library.

Actual Behavior:
1. Upon completing the image upload, the screen goes blank, and no further content is displayed.
2. The uploaded image is not visible or accessible in the media library.

This issue significantly impairs the platform's ability to handle media assets and content, hampering the essential functionality of storing and accessing images. It is crucial to address this problem promptly to ensure that users can seamlessly upload and manage images within the media library. Please investigate and resolve this issue to restore proper functionality and visibility of uploaded images in the media library.

https://www.loom.com/share/6d7ba396290d41308af9620224e5588c

**Comment by MIGUELez11** [comment]
Cannot reproduce, in all my environments is working, maybe some asset got stuck and is failing the full list assets process?
