### ISSUE TITLE
Shared with Me" Library Section Not Functional - No Redirection

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#58]
The "Shared with Me" section in the library is currently non-functional and fails to redirect users to the expected destination. As a result, users are unable to access and view items or files that have been shared with them by others.

Steps to Reproduce:
1. Log in to the platform.
2. Navigate to the library section.
3. Click on the "Shared with Me" section.

Expected Behavior:
1. Upon clicking the "Shared with Me" section, users should be redirected to a page displaying items or files that have been shared with them by other users.

Actual Behavior:
1. Clicking on the "Shared with Me" section does not trigger any redirection or display any content.
2. Users are unable to access or view items shared with them by others.

The "Shared with Me" functionality is an integral part of the collaboration and file-sharing features, and its current non-functional state severely hinders users from accessing important shared resources. Addressing this issue promptly will significantly enhance the platform's collaborative capabilities and user experience. Please investigate and rectify the problem to restore the "Shared with Me" section's functionality.

https://www.loom.com/share/5c6fd27ea92b475a8579316a7b9c2e20

**Comment by MIGUELez11** [comment]
This is currently working in the dev branch, so if present in the current main branch will be fixed shortly. Sorry for the inconveniences.
