### ISSUE TITLE
Blank Screen Encountered When Accessing Media Library with Admin Account

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#60]
An issue has been identified when attempting to access the media library using the admin account, causing the entire screen to go blank. As a result, no content or media assets are displayed within the media library, rendering it inaccessible to the admin account.

Steps to Reproduce:
1. Log in to the platform using the admin account.
2. Navigate to the media library section.
3. Attempt to access the media library.

Expected Behavior:
1. Upon accessing the media library, all media assets and files should be displayed and accessible to the admin account.

Actual Behavior:
1. When attempting to access the media library, the entire screen goes blank, and no media assets or content are visible.

This issue severely hampers the admin account's ability to manage media assets and content on the platform. As an admin, having access to the media library is essential for adding, removing, and organizing multimedia resources efficiently. It is crucial to investigate and resolve this problem promptly to restore proper functionality and visibility of the media library for the admin account. Please address this issue to ensure that the media library can be accessed without encountering a blank screen.

https://www.loom.com/share/9e713155fb534b6bb9c1ac8284829b41

Branch name: dev

**Comment by MIGUELez11** [comment]
Hello, this has been fixed by @Cerberupo in dev branch
