### ISSUE TITLE
Video Not Displayed in "Media Files" and "Shared with Me" Sections for Student Account

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#61]
An issue has been identified where a video uploaded from the admin account and marked as "public" is not appearing in the "Media Files" and "Shared with Me" sections when accessed from a student account. The expected behavior is that the video should be visible and accessible to all users once it has been marked as public.

Steps to Reproduce:
1. Log in to the admin account.
2. Upload a video to the platform and set its visibility to "public."
3. Log out from the admin account.
4. Log in to a student account.
5. Navigate to the "Media Files" section and search for the uploaded video.
6. Check the "Shared with Me" section to see if the video is visible there.

Expected Behavior:
1. The video uploaded from the admin account and marked as "public" should be visible in both the "Media Files" and "Shared with Me" sections when accessed from a student account.

Actual Behavior:
1. Despite setting the video as "public," it is not displayed in the "Media Files" and "Shared with Me" sections for the student account.

This issue restricts students from accessing videos that have been designated as public, limiting their ability to benefit from shared educational content. Resolving this problem is essential to ensure that videos marked as public are accessible to all users, promoting an inclusive and collaborative learning environment. Please investigate and rectify this issue to enable students to view and access videos that are publicly available to them.

https://www.loom.com/share/948e97c000e84eb1bc0fe71985959cd2?sid=3dc69291-b55e-4ccb-a06e-2fbebfb88028

**Comment by MIGUELez11** [comment]
I will raise the bug for a UX review.

**Comment by fmniloyuk** [comment]
@MIGUELez11 Any update on this?
