### ISSUE TITLE
"Virtual Classroom" Link Redirects to "about:blank" Page in Student Account

### ISSUE THREAD

**Issue by fmniloyuk** [leemonade/leemons#66]
When using the admin account to add a meeting link under the "Virtual classroom (video-call link)" section in the "Academic Portfolio Tree" page, the link appears as expected. However, when accessing the student account and clicking on the "Virtual Classroom" link from the student dashboard, it redirects to an "about:blank" page in the Chrome browser. As a result, the student is unable to access the designated virtual classroom.

Steps to Reproduce:
1. Log in to the platform using the admin account.
2. Navigate to the "Academic Portfolio Tree" page.
3. Locate the "Virtual classroom (video-call link)" section under "Groups of classe."
4. Add a meeting link to the section and click on the "Save Changes" button.
5. Log out from the admin account.
6. Log in to the test student account.
7. Access the student dashboard and click on the "Virtual Classroom" link.

Expected Behavior:
1. After clicking on the "Virtual Classroom" link from the student dashboard, the designated virtual classroom should open in the browser, allowing the student to join the video-call meeting.

Actual Behavior:
1. Clicking on the "Virtual Classroom" link from the student dashboard redirects to an "about:blank" page in the Chrome browser, preventing access to the designated virtual classroom.

This issue obstructs students from accessing the virtual classroom for their enrolled programs, hindering their ability to participate in video-call meetings and engage with the learning process effectively. Resolving this problem is crucial to ensure seamless access to virtual classrooms and promote a smooth and interactive learning experience for students. Please investigate and address this issue to enable the "Virtual Classroom" link to function correctly in the student account.

https://www.loom.com/share/7d01be06d0154638a74acad01f4687ba

**Comment by codebeginer** [comment]
Problem
<img width="860" alt="image" src="https://github.com/leemonade/leemons/assets/12094877/fca9fd50-c621-4dd3-9d5e-5247b7748f5f">

Solution
<img width="769" alt="image" src="https://github.com/leemonade/leemons/assets/12094877/8ee0d696-4539-4eb2-8806-9decd19e1d2e">
